Port Tomorrow Theme
Iron-E/nvim-highlite pull request #37
Opened 2024-09-05 14:46 UTC by n8tlarsen

First of all, nvim-highlite is a real gem among nvim theme packages. The ability to port existing themes or easily make new ones is a treat. I've used [Tomorrow Theme](https://github.com/chriskempson/tomorrow-theme) for a number of years now, but it lacks Treesitter support so I'm adding it here.

2024-09-07 16:07 UTC, Iron-E requested changes
Thank you for the kind words :)

I hoped that this plugin would be able to serve this sort of purpose. If you found the documentation for this process unclear in any way, I would be happy to receive feedback!

I only have a small nit, and then I'll be happy to merge whenever you are happy with it.

2024-09-07 16:07 UTC, Iron-E commented on lua/highlite/color/palette/tomorrow-night-blue.lua
> +	purple = 0xEBBBFF
We should put `local` before these variables as well, or else they will be set globally :)

2024-09-07 16:07 UTC, Iron-E commented on lua/highlite/color/palette/tomorrow-night-bright.lua
> +	purple = 0xC397D8
See comment on `tomorrow-night-blue` palette

2024-09-07 16:07 UTC, Iron-E commented on lua/highlite/color/palette/tomorrow-night-eighties.lua
> +	purple = 0xCC99CC
See comment on `tomorrow-night-blue` palette

2024-09-07 16:07 UTC, Iron-E commented on lua/highlite/color/palette/tomorrow-night.lua
> +	purple = 0xB294BB
See comment on `tomorrow-night-blue` palette

2024-09-07 16:07 UTC, Iron-E commented on lua/highlite/color/palette/tomorrow.lua
> +	purple = 0x8959A8
See comment on `tomorrow-night-blue` palette

2024-11-21 15:59 UTC, n8tlarsen commented
@Iron-E I'm not super familiar with Lua so thanks for the suggestion. Should be ready to merge now.

2024-11-21 16:10 UTC, Iron-E approved these changes

2024-11-21 16:11 UTC, merged

2024-11-21 16:12 UTC, Iron-E commented
Glad I could help 🙂 thanks for the PR!